name: Validate File Names

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # 手動トリガー有効化

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate file names
      run: |
        INVALID_CHARS='[<>:"/\\|?*]'
        git branch
        git diff --name-only --diff-filter=A origin/${{ github.base_ref }}
        INVALID_FILES=$(git diff --name-only --diff-filter=A origin/${{ github.base_ref }} | grep -E "$INVALID_CHARS" || true)
        if [ -n "$INVALID_FILES" ]; then
          echo "❌ Invalid file names detected:"
          echo "$INVALID_FILES"
          echo "::set-output name=invalid_files::$INVALID_FILES"
          exit 1
        else
          echo "✅ Invalid file names not detected"
        fi
      id: validate

    - name: Comment on PR
      if: steps.validate.outcome == 'failure'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: "File Name Validation Result"
        message: |
          ❌ Some file names contain characters invalid on Windows:
          ```
          ${{ steps.validate.outputs.invalid_files }}
          ```
    - name: All files are valid
      if: steps.check_invalid_names.outputs.invalid_files == 'false'
      run: echo "✅ All file names are valid for Windows."
