name: Validate File Names

on:
  push:
  pull_request:
  workflow_dispatch: # 手動トリガー有効化

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Fetch
      run: git fetch --prune --unshallow


    - name: ファイル名のチェック
      id: validate
      env:
        PR_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        INVALID_CHARS='[<>:"\\|?*]'
        INVALID_FILES=$(git diff --name-only --diff-filter=A origin/main | grep -E "$INVALID_CHARS" || true)
        if [ -n "$INVALID_FILES" ]; then
          echo -e "
            ❌無効なファイル名が検出されました：ファイル名に使用できない文字（例: < > : \" \\ | ? *）が含まれています。
            ```
            $INVALID_FILES
            ```
          " | tee /tmp/comment
          gh pr comment "${PR_NUMBER}" -F /tmp/comment
          exit 1
        else
          echo "✅無効なファイル名は検出されませんでした" | tee /tmp/comment
          gh pr comment "${PR_NUMBER}" -F /tmp/comment
        fi
