name: Validate File Names

on:
  push:
  workflow_dispatch: # 手動トリガー有効化

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Fetch
      run: git fetch --prune --unshallow

    - name: ファイル名のチェック
      id: validate
      run: |
        INVALID_CHARS='[<>:"/\\|?*]'
        INVALID_FILES=$(git diff --name-only --diff-filter=A origin/${{ github.base_ref }} | grep -E "$INVALID_CHARS" || true)

    - name: PRへのコメント（異常系）
      if: steps.validate.outcome == 'failure'
      env:
        PR_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo -e "
          ❌無効なファイル名が検出されました：ファイル名に使用できない文字（例: < > : \" / \\ | ? *）が含まれています。
          ```
          ${{ steps.validate.outputs.invalid_files }}
          ```
        " > /tmp/comment
        gh pr comment "${PR_NUMBER}" -F /tmp/comment

    - name: PRへのコメント（正常系）
      if: steps.check_invalid_names.outputs.invalid_files == 'false'
      run:  |
        echo "✅無効なファイル名は検出されませんでした" > /tmp/comment
        gh pr comment "${PR_NUMBER}" -F /tmp/comment
